### ISSUE TITLE
Add Datepicker demo component

### ISSUE THREAD

**Issue by akserg** [akserg/angular.dart.ui.demo#12]

**Comment by akserg** [comment]
Need to fix bug in ANgularDart UI:

type 'DatepickerDemoComponent' is not a subtype of type 'Map' of 'prototype'.

STACKTRACE:
#0      PrototypeMap.PrototypeMap (package:angular/change_detection/prototype_map.dart:7:21)
#1      DatepickerPopup.scope= (package:angular_ui/datepicker/popup.dart:55:45)
#2      ElementBinder._link (package:angular/core_dom/element_binder.dart:231:21)
#3      ElementBinder.bind (package:angular/core_dom/element_binder.dart:310:10)
#4      ViewFactory._bindTagged (package:angular/core_dom/view_factory.dart:79:36)
#5      ViewFactory._link (package:angular/core_dom/view_factory.dart:119:24)
#6      ViewFactory.call (package:angular/core_dom/view_factory.dart:58:10)
#7      BoundTranscludingComponentFactory.call.<anonymous closure>.<anonymous closure> (package:angular/core_dom/transcluding_component_factory.dart:112:54)
#8      _rootRunUnary (dart:async/zone.dart:902)
#9      _ZoneDelegate.runUnary (dart:async/zone.dart:508)
#10     _onRunUnary.<anonymous closure> (package:angular/core/zone.dart:122:63)
#11     VmTurnZone._onRunBase (package:angular/core/zone.dart:104:16)
#12     _onRunUnary (package:angular/core/zone.dart:122:17)
#13     _CustomZone.runUnary (dart:async/zone.dart:804)
#14     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:484)
#15     _Future._propagateToListeners (dart:async/future_impl.dart:567)
#16     _Future._completeWithValue (dart:async/future_impl.dart:358)
#17     _Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:412)
#18     _rootRun (dart:async/zone.dart:891)
#19     _ZoneDelegate.run (dart:async/zone.dart:501)
#20     _onScheduleMicrotask.<anonymous closure> (package:angular/core/zone.dart:127:45)
#21     RootScope._runAsyncFns (package:angular/core/scope.dart:924:25)
#22     RootScope.digest (package:angular/core/scope.dart:813:38)
#23     Scope.apply (package:angular/core/scope.dart:316:24)
#24     RootScope.RootScope.<anonymous closure> (package:angular/core/scope.dart:768:12)
#25     _rootRun (dart:async/zone.dart:895)
#26     _ZoneDelegate.run (dart:async/zone.dart:501)
#27     VmTurnZone._finishTurn (package:angular/core/zone.dart:168:21)
#28     VmTurnZone._onRunBase (package:angular/core/zone.dart:111:43)
#29     _onRunUnary (package:angular/core/zone.dart:122:17)
#30     _CustomZone.runUnary (dart:async/zone.dart:804)
#31     _CustomZone.runUnaryGuarded (dart:async/zone.dart:712)
#32     _CustomZone.bindUnaryCallback.<anonymous closure> (dart:async/zone.dart:738)

**Comment by ainjayla** [comment]
What is the status of this issue? I can't figure out how to use this popup datepicker at all.

**Comment by akserg** [comment]
Busy with other projects, but will try to find time to fix this one for you.

**Comment by akserg** [comment]
Hi,

I tried to fix the issue, but unfortunately it takes more time than I expect. I'm busy with [Angular2 UI Bootstrap components](https://github.com/akserg/angular2-ui-bootstrap) and don't plan to fix this issue in nearest future. Sorry about that.
